import { BusOption } from '../../types/booking';
import { BUS_IMAGES } from '../../assets/travelImages';

export const BUS_INVENTORY: BusOption[] = [
  // 1. Bengaluru -> Chennai
  {
    id: 'bus-blr-maa-volvo9600',
    service: 'bus',
    operator: 'IntrCity SmartBus',
    identifier: 'VOLVO-9600-BLR',
    subType: 'Volvo 9600 Multi-Axle AC Sleeper (2+1)',
    busType: 'AC Sleeper (2+1)',
    seatType: 'Sleeper',
    originCity: 'Bengaluru',
    originCode: 'BLR',
    boardingPoint: 'Majestic Anand Rao Circle (Private AC Lounge)',
    originStationOrTerminal: 'Majestic Anand Rao Circle',
    destinationCity: 'Chennai',
    destinationCode: 'MAA',
    droppingPoint: 'Koyambedu CMBT Omni Bus Terminus',
    destinationStationOrTerminal: 'Koyambedu CMBT',
    departureTime: '10:30 PM',
    arrivalTime: '05:15 AM',
    duration: '06h 45m',
    stops: 2,
    baseFare: 850,
    availableUnits: 14,
    rating: 4.8,
    image: BUS_IMAGES[0]?.src,
    amenities: ['Private Berth Curtains', 'USB-C Fast Charging', 'Fresh Blanket & Pillow', 'Live GPS Tracking', 'Lounge Boarding'],
  },
  {
    id: 'bus-blr-maa-airawat',
    service: 'bus',
    operator: 'KSRTC Airawat Club Class',
    identifier: 'KA-01-F-9122',
    subType: 'Volvo B11R Multi-Axle Semi-Sleeper',
    busType: 'Semi-Sleeper',
    seatType: 'Semi-Sleeper',
    originCity: 'Bengaluru',
    originCode: 'BLR',
    boardingPoint: 'Shantinagar KSRTC Bus Station Bay 3',
    originStationOrTerminal: 'Shantinagar Station',
    destinationCity: 'Chennai',
    destinationCode: 'MAA',
    droppingPoint: 'Koyambedu Omni Terminus',
    destinationStationOrTerminal: 'Koyambedu Omni Bus Terminus',
    departureTime: '11:15 PM',
    arrivalTime: '05:45 AM',
    duration: '06h 30m',
    stops: 1,
    baseFare: 790,
    availableUnits: 20,
    rating: 4.9,
    image: BUS_IMAGES[1]?.src,
    amenities: ['Ergonomic Calf Support', 'Complimentary Mineral Water', 'Highway Express Run', 'Emergency SOS'],
  },
  {
    id: 'bus-blr-maa-zingbus',
    service: 'bus',
    operator: 'Zingbus Electric Intercity',
    identifier: 'ZEV-401',
    subType: 'Zero-Emission Luxury Intercity Coach',
    busType: 'Electric Coach',
    seatType: 'AC Seater',
    originCity: 'Bengaluru',
    originCode: 'BLR',
    boardingPoint: 'Indiranagar Zing Premium Lounge',
    originStationOrTerminal: 'Indiranagar Lounge',
    destinationCity: 'Chennai',
    destinationCode: 'MAA',
    droppingPoint: 'Guindy Metro Station Bay 2',
    destinationStationOrTerminal: 'Guindy Metro Station',
    departureTime: '06:00 AM',
    arrivalTime: '12:15 PM',
    duration: '06h 15m',
    stops: 1,
    baseFare: 699,
    availableUnits: 16,
    rating: 4.7,
    image: BUS_IMAGES[3]?.src,
    amenities: ['Silent Cabin', 'Zero Carbon Emission', 'High-Speed Free Wi-Fi', 'Clean Restroom Halt'],
  },

  // 2. Mumbai -> Goa
  {
    id: 'bus-bom-goi-vrl',
    service: 'bus',
    operator: 'VRL Travels',
    identifier: 'VRL-SC-8812',
    subType: 'Scania Multi-Axle AC Sleeper (2+1)',
    busType: 'AC Sleeper (2+1)',
    seatType: 'Sleeper',
    originCity: 'Mumbai',
    originCode: 'BOM',
    boardingPoint: 'Borivali West Gokul Hotel',
    originStationOrTerminal: 'Borivali West',
    destinationCity: 'Goa',
    destinationCode: 'GOI',
    droppingPoint: 'Panaji KTC Central Bus Stand',
    destinationStationOrTerminal: 'Panaji KTC Bus Stand',
    departureTime: '07:00 PM',
    arrivalTime: '07:30 AM',
    duration: '12h 30m',
    stops: 3,
    baseFare: 1250,
    availableUnits: 8,
    rating: 4.7,
    image: BUS_IMAGES[0]?.src,
    amenities: ['Spacious Berths', 'USB Charging', 'Dedicated Food Court Break', 'Live Tracking'],
  },
  {
    id: 'bus-bom-goi-paulo',
    service: 'bus',
    operator: 'Paulo Travels Luxury',
    identifier: 'PAULO-VOLVO-96',
    subType: 'Volvo 9600 Night Queen Sleeper',
    busType: 'AC Sleeper (2+1)',
    seatType: 'Sleeper',
    originCity: 'Mumbai',
    originCode: 'BOM',
    boardingPoint: 'Dadar TT Circle Asiad Bus Stop',
    originStationOrTerminal: 'Dadar TT Circle',
    destinationCity: 'Goa',
    destinationCode: 'GOI',
    droppingPoint: 'Mapusa City Bus Stand',
    destinationStationOrTerminal: 'Mapusa Bus Stand',
    departureTime: '08:30 PM',
    arrivalTime: '08:45 AM',
    duration: '12h 15m',
    stops: 2,
    baseFare: 1390,
    availableUnits: 12,
    rating: 4.8,
    image: BUS_IMAGES[1]?.src,
    amenities: ['Memory Foam Mattress', 'Reading Lamp', 'Water Bottle', 'SOS Button'],
  },

  // 3. Delhi -> Chandigarh
  {
    id: 'bus-del-ixc-zingbus',
    service: 'bus',
    operator: 'Zingbus Electric Intercity',
    identifier: 'ZEV-102',
    subType: 'Zero-Emission Luxury Intercity Coach',
    busType: 'Electric Coach',
    seatType: 'AC Seater',
    originCity: 'Delhi',
    originCode: 'DEL',
    boardingPoint: 'ISBT Kashmere Gate Metro Gate 1',
    originStationOrTerminal: 'ISBT Kashmere Gate',
    destinationCity: 'Chandigarh',
    destinationCode: 'IXC',
    droppingPoint: 'Sector 43 ISBT Terminus',
    destinationStationOrTerminal: 'Sector 43 ISBT',
    departureTime: '06:30 AM',
    arrivalTime: '11:15 AM',
    duration: '04h 45m',
    stops: 1,
    baseFare: 599,
    availableUnits: 19,
    rating: 4.6,
    image: BUS_IMAGES[3]?.src,
    amenities: ['Whisper-Quiet Electric Ride', 'Air Quality HEPA Filter', 'USB-C Charging', 'Live ETA Tracking'],
  },
  {
    id: 'bus-del-ixc-himsuta',
    service: 'bus',
    operator: 'HRTC Himsuta Super Luxury',
    identifier: 'HP-63-A-2024',
    subType: 'Volvo B11R Highway Master',
    busType: 'Semi-Sleeper',
    seatType: 'Semi-Sleeper',
    originCity: 'Delhi',
    originCode: 'DEL',
    boardingPoint: 'ISBT Kashmere Gate Counter 14',
    originStationOrTerminal: 'ISBT Kashmere Gate',
    destinationCity: 'Chandigarh',
    destinationCode: 'IXC',
    droppingPoint: 'Sector 17 Bus Stand',
    destinationStationOrTerminal: 'Sector 17 Bus Stand',
    departureTime: '01:30 PM',
    arrivalTime: '06:15 PM',
    duration: '04h 45m',
    stops: 1,
    baseFare: 650,
    availableUnits: 25,
    rating: 4.8,
    image: BUS_IMAGES[1]?.src,
    amenities: ['Government Certified Safety', 'Smooth Highway Run', 'Mineral Water', 'Reclining Comfort'],
  },

  // 4. Hyderabad -> Bengaluru
  {
    id: 'bus-hyd-blr-srs',
    service: 'bus',
    operator: 'SRS Travels',
    identifier: 'SRS-BB-4109',
    subType: 'BharatBenz AC Sleeper (2+1)',
    busType: 'AC Sleeper (2+1)',
    seatType: 'Sleeper',
    originCity: 'Hyderabad',
    originCode: 'HYD',
    boardingPoint: 'MGBS Central Bus Station Platform 9',
    originStationOrTerminal: 'MGBS Central',
    destinationCity: 'Bengaluru',
    destinationCode: 'BLR',
    droppingPoint: 'Majestic Anand Rao Circle',
    destinationStationOrTerminal: 'Majestic Anand Rao Circle',
    departureTime: '09:45 PM',
    arrivalTime: '06:30 AM',
    duration: '08h 45m',
    stops: 2,
    baseFare: 950,
    availableUnits: 15,
    rating: 4.5,
    image: BUS_IMAGES[2]?.src,
    amenities: ['Individual Reading Lights', 'Soft Warm Blanket', 'Punctual Dispatch', 'Live Tracking'],
  },

  // 5. Chennai -> Madurai
  {
    id: 'bus-maa-mdu-orange',
    service: 'bus',
    operator: 'Orange Tours & Travels',
    identifier: 'ORANGE-MB-702',
    subType: 'Mercedes-Benz Multi-Axle AC Sleeper',
    busType: 'AC Sleeper (2+1)',
    seatType: 'Sleeper',
    originCity: 'Chennai',
    originCode: 'MAA',
    boardingPoint: 'Koyambedu Omni Bus Stand Bay 4',
    originStationOrTerminal: 'Koyambedu Omni Bus Stand',
    destinationCity: 'Madurai',
    destinationCode: 'MDU',
    droppingPoint: 'Mattuthavani Integrated Bus Terminal',
    destinationStationOrTerminal: 'Mattuthavani Terminal',
    departureTime: '10:15 PM',
    arrivalTime: '05:45 AM',
    duration: '07h 30m',
    stops: 1,
    baseFare: 820,
    availableUnits: 14,
    rating: 4.7,
    image: BUS_IMAGES[0]?.src,
    amenities: ['Air Suspension Glide', 'High-Density Mattress', 'Bottle Holder', 'Trained Co-Driver'],
  },

  // 6. Bengaluru -> Mysuru
  {
    id: 'bus-blr-myr-airawat',
    service: 'bus',
    operator: 'KSRTC Airawat Diamond Class',
    identifier: 'KA-09-F-1120',
    subType: 'Scania Multi-Axle AC Seater Coach',
    busType: 'AC Seater',
    seatType: 'AC Seater',
    originCity: 'Bengaluru',
    originCode: 'BLR',
    boardingPoint: 'Satellite Bus Station (Mysore Road)',
    originStationOrTerminal: 'Satellite Bus Station',
    destinationCity: 'Mysuru',
    destinationCode: 'MYA',
    droppingPoint: 'Suburban KSRTC Bus Stand',
    destinationStationOrTerminal: 'Suburban Bus Stand',
    departureTime: '08:30 AM',
    arrivalTime: '11:15 AM',
    duration: '02h 45m',
    stops: 1,
    baseFare: 380,
    availableUnits: 34,
    rating: 4.8,
    image: BUS_IMAGES[1]?.src,
    amenities: ['Expressway Run', 'Reclining Push-Back Seats', 'Scenic Windows', 'Clean Interior'],
  },

  // 7. Delhi -> Agra
  {
    id: 'bus-del-agr-intrcity',
    service: 'bus',
    operator: 'IntrCity SmartBus',
    identifier: 'VOLVO-AGR-EXPR',
    subType: 'Volvo B11R Luxury Intercity',
    busType: 'Semi-Sleeper',
    seatType: 'Semi-Sleeper',
    originCity: 'Delhi',
    originCode: 'DEL',
    boardingPoint: 'Akshardham Metro Station Smart Lounge',
    originStationOrTerminal: 'Akshardham Lounge',
    destinationCity: 'Agra',
    destinationCode: 'AGR',
    droppingPoint: 'Agra ISBT / Idgah Bus Stand',
    destinationStationOrTerminal: 'Agra ISBT',
    departureTime: '07:15 AM',
    arrivalTime: '10:45 AM',
    duration: '03h 30m',
    stops: 1,
    baseFare: 450,
    availableUnits: 28,
    rating: 4.7,
    image: BUS_IMAGES[0]?.src,
    amenities: ['Yamuna Expressway Non-Stop', 'Captain Assist', 'Complimentary Water Bottle', 'Wi-Fi'],
  },
];
