import { FlightOption } from '../../types/booking';
import { FLIGHT_IMAGES } from '../../assets/travelImages';

export const FLIGHT_INVENTORY: FlightOption[] = [
  // 1. Chennai (MAA) -> Delhi (DEL)
  {
    id: 'fl-maa-del-6e204',
    service: 'flight',
    operator: 'IndiGo Airlines',
    identifier: '6E 204',
    subType: 'Airbus A321neo',
    originCity: 'Chennai',
    originCode: 'MAA',
    originStationOrTerminal: 'Terminal 1 (Domestic)',
    destinationCity: 'Delhi',
    destinationCode: 'DEL',
    destinationStationOrTerminal: 'Terminal 3 (IGI)',
    departureTime: '06:10 AM',
    arrivalTime: '08:55 AM',
    duration: '2h 45m',
    stops: 0,
    baseFare: 4899,
    availableUnits: 18,
    rating: 4.8,
    image: FLIGHT_IMAGES[1]?.src,
    amenities: ['Non-stop Corridor', 'USB Fast Charging', 'Pre-book Meals', 'Auto Web Check-in'],
    baggage: 'Cabin: 7 kg, Check-in: 15 kg',
    isRefundable: true,
    isInternational: false,
    cabinClasses: [
      { className: 'Economy', fare: 4899, available: 14 },
      { className: 'Premium Economy', fare: 6999, available: 4 },
    ],
  },
  {
    id: 'fl-maa-del-ai440',
    service: 'flight',
    operator: 'Air India',
    identifier: 'AI 440',
    subType: 'Boeing 787-8 Dreamliner',
    originCity: 'Chennai',
    originCode: 'MAA',
    originStationOrTerminal: 'Terminal 4',
    destinationCity: 'Delhi',
    destinationCode: 'DEL',
    destinationStationOrTerminal: 'Terminal 3 (IGI)',
    departureTime: '05:45 PM',
    arrivalTime: '08:35 PM',
    duration: '2h 50m',
    stops: 0,
    baseFare: 5299,
    availableUnits: 24,
    rating: 4.7,
    image: FLIGHT_IMAGES[0]?.src,
    amenities: ['Complimentary Hot Meals', 'Widebody Comfort', '25 kg Luggage', 'In-Flight Audio'],
    baggage: 'Cabin: 7 kg, Check-in: 25 kg',
    isRefundable: true,
    isInternational: false,
    cabinClasses: [
      { className: 'Economy', fare: 5299, available: 18 },
      { className: 'Premium Economy', fare: 7650, available: 4 },
      { className: 'Business', fare: 17800, available: 2 },
    ],
  },

  // 2. Chennai (MAA) -> Mumbai (BOM)
  {
    id: 'fl-maa-bom-6e5318',
    service: 'flight',
    operator: 'IndiGo Airlines',
    identifier: '6E 5318',
    subType: 'Airbus A320neo',
    originCity: 'Chennai',
    originCode: 'MAA',
    originStationOrTerminal: 'Terminal 1',
    destinationCity: 'Mumbai',
    destinationCode: 'BOM',
    destinationStationOrTerminal: 'Terminal 1 (CSMIA)',
    departureTime: '07:20 AM',
    arrivalTime: '09:15 AM',
    duration: '1h 55m',
    stops: 0,
    baseFare: 3699,
    availableUnits: 16,
    rating: 4.7,
    image: FLIGHT_IMAGES[1]?.src,
    amenities: ['Morning Direct', 'Standard Carry-on', 'Beverage Cart'],
    baggage: 'Cabin: 7 kg, Check-in: 15 kg',
    isRefundable: false,
    isInternational: false,
    cabinClasses: [
      { className: 'Economy', fare: 3699, available: 16 },
      { className: 'Premium Economy', fare: 5499, available: 5 },
    ],
  },
  {
    id: 'fl-maa-bom-ai672',
    service: 'flight',
    operator: 'Air India',
    identifier: 'AI 672',
    subType: 'Airbus A321neo',
    originCity: 'Chennai',
    originCode: 'MAA',
    originStationOrTerminal: 'Terminal 1',
    destinationCity: 'Mumbai',
    destinationCode: 'BOM',
    destinationStationOrTerminal: 'Terminal 2 (CSMIA)',
    departureTime: '08:30 PM',
    arrivalTime: '10:30 PM',
    duration: '2h 00m',
    stops: 0,
    baseFare: 4199,
    availableUnits: 20,
    rating: 4.8,
    image: FLIGHT_IMAGES[0]?.src,
    amenities: ['Dinner Included', 'Extra Legroom Available', '25 kg Baggage'],
    baggage: 'Cabin: 7 kg, Check-in: 25 kg',
    isRefundable: true,
    isInternational: false,
    cabinClasses: [
      { className: 'Economy', fare: 4199, available: 16 },
      { className: 'Business', fare: 13500, available: 4 },
    ],
  },

  // 3. Chennai (MAA) -> Bengaluru (BLR)
  {
    id: 'fl-maa-blr-6e338',
    service: 'flight',
    operator: 'IndiGo Airlines',
    identifier: '6E 338',
    subType: 'ATR 72-600',
    originCity: 'Chennai',
    originCode: 'MAA',
    originStationOrTerminal: 'Terminal 1',
    destinationCity: 'Bengaluru',
    destinationCode: 'BLR',
    destinationStationOrTerminal: 'Terminal 1',
    departureTime: '08:45 AM',
    arrivalTime: '09:40 AM',
    duration: '0h 55m',
    stops: 0,
    baseFare: 2199,
    availableUnits: 28,
    rating: 4.6,
    image: FLIGHT_IMAGES[1]?.src,
    amenities: ['Rapid Intercity Hop', 'Propjet Experience', 'Punctual Dispatch'],
    baggage: 'Cabin: 7 kg, Check-in: 15 kg',
    isRefundable: false,
    isInternational: false,
    cabinClasses: [
      { className: 'Economy', fare: 2199, available: 28 },
    ],
  },
  {
    id: 'fl-maa-blr-qp1502',
    service: 'flight',
    operator: 'Akasa Air',
    identifier: 'QP 1502',
    subType: 'Boeing 737 MAX 8',
    originCity: 'Chennai',
    originCode: 'MAA',
    originStationOrTerminal: 'Terminal 1',
    destinationCity: 'Bengaluru',
    destinationCode: 'BLR',
    destinationStationOrTerminal: 'Terminal 2',
    departureTime: '04:15 PM',
    arrivalTime: '05:10 PM',
    duration: '0h 55m',
    stops: 0,
    baseFare: 2350,
    availableUnits: 22,
    rating: 4.8,
    image: FLIGHT_IMAGES[4]?.src,
    amenities: ['Eco Fuel Efficient', 'Café Akasa Gourmet', 'USB-C at Every Seat'],
    baggage: 'Cabin: 7 kg, Check-in: 15 kg',
    isRefundable: true,
    isInternational: false,
    cabinClasses: [
      { className: 'Economy', fare: 2350, available: 18 },
      { className: 'Premium Economy', fare: 3850, available: 4 },
    ],
  },

  // 4. Chennai (MAA) -> Hyderabad (HYD)
  {
    id: 'fl-maa-hyd-6e714',
    service: 'flight',
    operator: 'IndiGo Airlines',
    identifier: '6E 714',
    subType: 'Airbus A320neo',
    originCity: 'Chennai',
    originCode: 'MAA',
    originStationOrTerminal: 'Terminal 1',
    destinationCity: 'Hyderabad',
    destinationCode: 'HYD',
    destinationStationOrTerminal: 'Main Terminal',
    departureTime: '09:15 AM',
    arrivalTime: '10:30 AM',
    duration: '1h 15m',
    stops: 0,
    baseFare: 2999,
    availableUnits: 15,
    rating: 4.7,
    image: FLIGHT_IMAGES[1]?.src,
    amenities: ['Direct Flight', 'Web Check-in', 'Snack Bar'],
    baggage: 'Cabin: 7 kg, Check-in: 15 kg',
    isRefundable: true,
    isInternational: false,
    cabinClasses: [
      { className: 'Economy', fare: 2999, available: 15 },
      { className: 'Premium Economy', fare: 4800, available: 6 },
    ],
  },

  // 5. Delhi (DEL) -> Mumbai (BOM)
  {
    id: 'fl-del-bom-6e2134',
    service: 'flight',
    operator: 'IndiGo Airlines',
    identifier: '6E 2134',
    subType: 'Airbus A321neo',
    originCity: 'Delhi',
    originCode: 'DEL',
    originStationOrTerminal: 'Terminal 3 (IGI)',
    destinationCity: 'Mumbai',
    destinationCode: 'BOM',
    destinationStationOrTerminal: 'Terminal 2 (CSMIA)',
    departureTime: '06:15 AM',
    arrivalTime: '08:30 AM',
    duration: '2h 15m',
    stops: 0,
    baseFare: 4299,
    availableUnits: 14,
    rating: 4.8,
    image: FLIGHT_IMAGES[1]?.src,
    amenities: ['Golden Corridor Early Bird', 'USB Charging', 'Paid Meals', 'Standard Carry-on'],
    baggage: 'Cabin: 7 kg, Check-in: 15 kg',
    isRefundable: false,
    isInternational: false,
    cabinClasses: [
      { className: 'Economy', fare: 4299, available: 14 },
      { className: 'Premium Economy', fare: 6499, available: 6 },
      { className: 'Business', fare: 14200, available: 2 },
    ],
  },
  {
    id: 'fl-del-bom-ai805',
    service: 'flight',
    operator: 'Air India',
    identifier: 'AI 805',
    subType: 'Boeing 787-8 Dreamliner',
    originCity: 'Delhi',
    originCode: 'DEL',
    originStationOrTerminal: 'Terminal 3 (IGI)',
    destinationCity: 'Mumbai',
    destinationCode: 'BOM',
    destinationStationOrTerminal: 'Terminal 2 (CSMIA)',
    departureTime: '08:00 AM',
    arrivalTime: '10:15 AM',
    duration: '2h 15m',
    stops: 0,
    baseFare: 4699,
    availableUnits: 22,
    rating: 4.7,
    image: FLIGHT_IMAGES[0]?.src,
    amenities: ['Complimentary Hot Breakfast', '25 kg Baggage', 'Widebody Comfort'],
    baggage: 'Cabin: 7 kg, Check-in: 25 kg',
    isRefundable: true,
    isInternational: false,
    cabinClasses: [
      { className: 'Economy', fare: 4699, available: 22 },
      { className: 'Premium Economy', fare: 7100, available: 8 },
      { className: 'Business', fare: 16500, available: 4 },
    ],
  },
  {
    id: 'fl-del-bom-sg8169',
    service: 'flight',
    operator: 'SpiceJet',
    identifier: 'SG 8169',
    subType: 'Boeing 737-800',
    originCity: 'Delhi',
    originCode: 'DEL',
    originStationOrTerminal: 'Terminal 1D',
    destinationCity: 'Mumbai',
    destinationCode: 'BOM',
    destinationStationOrTerminal: 'Terminal 1',
    departureTime: '07:30 PM',
    arrivalTime: '10:00 PM',
    duration: '2h 30m',
    stops: 0,
    baseFare: 3699,
    availableUnits: 18,
    rating: 4.3,
    image: FLIGHT_IMAGES[4]?.src,
    amenities: ['Pre-book Hot Snacks', 'Spicexpress Priority'],
    baggage: 'Cabin: 7 kg, Check-in: 15 kg',
    isRefundable: false,
    isInternational: false,
    cabinClasses: [
      { className: 'Economy', fare: 3699, available: 18 },
      { className: 'Premium Economy', fare: 5299, available: 5 },
    ],
  },

  // 6. Mumbai (BOM) -> Bengaluru (BLR)
  {
    id: 'fl-bom-blr-6e488',
    service: 'flight',
    operator: 'IndiGo Airlines',
    identifier: '6E 488',
    subType: 'Airbus A321neo',
    originCity: 'Mumbai',
    originCode: 'BOM',
    originStationOrTerminal: 'Terminal 1',
    destinationCity: 'Bengaluru',
    destinationCode: 'BLR',
    destinationStationOrTerminal: 'Terminal 1',
    departureTime: '06:45 AM',
    arrivalTime: '08:30 AM',
    duration: '1h 45m',
    stops: 0,
    baseFare: 3499,
    availableUnits: 20,
    rating: 4.8,
    image: FLIGHT_IMAGES[1]?.src,
    amenities: ['Express Commute', 'Snack Bar', 'Web Check-in'],
    baggage: 'Cabin: 7 kg, Check-in: 15 kg',
    isRefundable: true,
    isInternational: false,
    cabinClasses: [
      { className: 'Economy', fare: 3499, available: 20 },
      { className: 'Premium Economy', fare: 5199, available: 6 },
    ],
  },
  {
    id: 'fl-bom-blr-ai639',
    service: 'flight',
    operator: 'Air India',
    identifier: 'AI 639',
    subType: 'Airbus A320neo',
    originCity: 'Mumbai',
    originCode: 'BOM',
    originStationOrTerminal: 'Terminal 2',
    destinationCity: 'Bengaluru',
    destinationCode: 'BLR',
    destinationStationOrTerminal: 'Terminal 2 (Garden)',
    departureTime: '07:15 PM',
    arrivalTime: '09:05 PM',
    duration: '1h 50m',
    stops: 0,
    baseFare: 3899,
    availableUnits: 15,
    rating: 4.7,
    image: FLIGHT_IMAGES[0]?.src,
    amenities: ['Warm Evening Meal', '25 kg Allowance', 'Lounge Access Available'],
    baggage: 'Cabin: 7 kg, Check-in: 25 kg',
    isRefundable: true,
    isInternational: false,
    cabinClasses: [
      { className: 'Economy', fare: 3899, available: 15 },
      { className: 'Business', fare: 12400, available: 3 },
    ],
  },

  // 7. Bengaluru (BLR) -> Delhi (DEL)
  {
    id: 'fl-blr-del-6e2102',
    service: 'flight',
    operator: 'IndiGo Airlines',
    identifier: '6E 2102',
    subType: 'Airbus A321neo',
    originCity: 'Bengaluru',
    originCode: 'BLR',
    originStationOrTerminal: 'Terminal 1',
    destinationCity: 'Delhi',
    destinationCode: 'DEL',
    destinationStationOrTerminal: 'Terminal 3',
    departureTime: '07:00 AM',
    arrivalTime: '09:45 AM',
    duration: '2h 45m',
    stops: 0,
    baseFare: 4999,
    availableUnits: 17,
    rating: 4.8,
    image: FLIGHT_IMAGES[1]?.src,
    amenities: ['Morning Executive Non-Stop', 'Fast Security Clearance', 'USB Port'],
    baggage: 'Cabin: 7 kg, Check-in: 15 kg',
    isRefundable: true,
    isInternational: false,
    cabinClasses: [
      { className: 'Economy', fare: 4999, available: 17 },
      { className: 'Premium Economy', fare: 7200, available: 5 },
    ],
  },
  {
    id: 'fl-blr-del-ai505',
    service: 'flight',
    operator: 'Air India',
    identifier: 'AI 505',
    subType: 'Boeing 787-8 Dreamliner',
    originCity: 'Bengaluru',
    originCode: 'BLR',
    originStationOrTerminal: 'Terminal 2',
    destinationCity: 'Delhi',
    destinationCode: 'DEL',
    destinationStationOrTerminal: 'Terminal 3',
    departureTime: '09:30 AM',
    arrivalTime: '12:20 PM',
    duration: '2h 50m',
    stops: 0,
    baseFare: 5499,
    availableUnits: 25,
    rating: 4.8,
    image: FLIGHT_IMAGES[0]?.src,
    amenities: ['Complimentary Meal & Drinks', 'Dreamliner Tint Windows', '25 kg Luggage'],
    baggage: 'Cabin: 7 kg, Check-in: 25 kg',
    isRefundable: true,
    isInternational: false,
    cabinClasses: [
      { className: 'Economy', fare: 5499, available: 25 },
      { className: 'Premium Economy', fare: 7800, available: 8 },
      { className: 'Business', fare: 18200, available: 4 },
    ],
  },

  // 8. Hyderabad (HYD) -> Delhi (DEL)
  {
    id: 'fl-hyd-del-6e218',
    service: 'flight',
    operator: 'IndiGo Airlines',
    identifier: '6E 218',
    subType: 'Airbus A320neo',
    originCity: 'Hyderabad',
    originCode: 'HYD',
    originStationOrTerminal: 'Main Terminal',
    destinationCity: 'Delhi',
    destinationCode: 'DEL',
    destinationStationOrTerminal: 'Terminal 3',
    departureTime: '06:20 AM',
    arrivalTime: '08:35 AM',
    duration: '2h 15m',
    stops: 0,
    baseFare: 3999,
    availableUnits: 20,
    rating: 4.7,
    image: FLIGHT_IMAGES[1]?.src,
    amenities: ['Direct Flight', 'Web Check-in', 'Snack Bar'],
    baggage: 'Cabin: 7 kg, Check-in: 15 kg',
    isRefundable: false,
    isInternational: false,
    cabinClasses: [
      { className: 'Economy', fare: 3999, available: 20 },
      { className: 'Premium Economy', fare: 5899, available: 6 },
    ],
  },

  // 9. INTERNATIONAL: Chennai (MAA) -> Dubai (DXB)
  {
    id: 'fl-maa-dxb-ek545',
    service: 'flight',
    operator: 'Emirates',
    identifier: 'EK 545',
    subType: 'Boeing 777-300ER',
    originCity: 'Chennai',
    originCode: 'MAA',
    originStationOrTerminal: 'Terminal 4 (International)',
    destinationCity: 'Dubai',
    destinationCode: 'DXB',
    destinationStationOrTerminal: 'Terminal 3 (Emirates Hub)',
    departureTime: '09:45 AM',
    arrivalTime: '12:35 PM',
    duration: '4h 20m',
    stops: 0,
    baseFare: 17499,
    availableUnits: 32,
    rating: 4.9,
    image: FLIGHT_IMAGES[2]?.src,
    amenities: ['ice On-Demand Entertainment', 'Multi-Course Halal Dining', '30 kg Luggage', 'Wi-Fi Onboard'],
    baggage: 'Cabin: 7 kg, Check-in: 30 kg',
    isRefundable: true,
    isInternational: true,
    cabinClasses: [
      { className: 'Economy', fare: 17499, available: 32 },
      { className: 'Premium Economy', fare: 28500, available: 10 },
      { className: 'Business', fare: 54000, available: 6 },
    ],
  },

  // 10. INTERNATIONAL: Delhi (DEL) -> Singapore (SIN)
  {
    id: 'fl-del-sin-sq401',
    service: 'flight',
    operator: 'Singapore Airlines',
    identifier: 'SQ 401',
    subType: 'Airbus A350-900',
    originCity: 'Delhi',
    originCode: 'DEL',
    originStationOrTerminal: 'Terminal 3 (International)',
    destinationCity: 'Singapore',
    destinationCode: 'SIN',
    destinationStationOrTerminal: 'Changi Airport Terminal 3',
    departureTime: '09:55 AM',
    arrivalTime: '06:10 PM',
    duration: '5h 45m',
    stops: 0,
    baseFare: 19899,
    availableUnits: 26,
    rating: 4.9,
    image: FLIGHT_IMAGES[3]?.src,
    amenities: ['KrisWorld 1,800+ Movies', 'Authentic Asian Dining', '30 kg Baggage', 'Changi Transit Access'],
    baggage: 'Cabin: 7 kg, Check-in: 30 kg',
    isRefundable: true,
    isInternational: true,
    cabinClasses: [
      { className: 'Economy', fare: 19899, available: 26 },
      { className: 'Premium Economy', fare: 33500, available: 8 },
      { className: 'Business', fare: 69000, available: 4 },
    ],
  },

  // 11. INTERNATIONAL: Mumbai (BOM) -> London Heathrow (LHR)
  {
    id: 'fl-bom-lhr-ba138',
    service: 'flight',
    operator: 'British Airways',
    identifier: 'BA 138',
    subType: 'Boeing 787-9 Dreamliner',
    originCity: 'Mumbai',
    originCode: 'BOM',
    originStationOrTerminal: 'Terminal 2 (CSMIA)',
    destinationCity: 'London',
    destinationCode: 'LHR',
    destinationStationOrTerminal: 'Terminal 5 (Heathrow)',
    departureTime: '02:15 AM',
    arrivalTime: '07:15 AM',
    duration: '9h 30m',
    stops: 0,
    baseFare: 42999,
    availableUnits: 30,
    rating: 4.8,
    image: FLIGHT_IMAGES[2]?.src,
    amenities: ['High Life Entertainment', 'Complimentary Bar Service', '2 x 23 kg Luggage', 'World Traveller'],
    baggage: 'Cabin: 10 kg, Check-in: 46 kg (2 bags)',
    isRefundable: true,
    isInternational: true,
    cabinClasses: [
      { className: 'Economy', fare: 42999, available: 30 },
      { className: 'Premium Economy', fare: 68500, available: 12 },
      { className: 'Business', fare: 145000, available: 5 },
    ],
  },

  // 12. INTERNATIONAL: Delhi (DEL) -> Bangkok (BKK)
  {
    id: 'fl-del-bkk-tg316',
    service: 'flight',
    operator: 'Thai Airways',
    identifier: 'TG 316',
    subType: 'Airbus A350-900',
    originCity: 'Delhi',
    originCode: 'DEL',
    originStationOrTerminal: 'Terminal 3',
    destinationCity: 'Bangkok',
    destinationCode: 'BKK',
    destinationStationOrTerminal: 'Suvarnabhumi International',
    departureTime: '11:55 PM',
    arrivalTime: '05:35 AM',
    duration: '4h 10m',
    stops: 0,
    baseFare: 14899,
    availableUnits: 25,
    rating: 4.8,
    image: FLIGHT_IMAGES[3]?.src,
    amenities: ['Smooth As Silk Hospitality', 'Authentic Thai Cuisine', '30 kg Luggage', 'Night Flight Sleep'],
    baggage: 'Cabin: 7 kg, Check-in: 30 kg',
    isRefundable: true,
    isInternational: true,
    cabinClasses: [
      { className: 'Economy', fare: 14899, available: 25 },
      { className: 'Premium Economy', fare: 24000, available: 8 },
      { className: 'Business', fare: 48000, available: 4 },
    ],
  },
];
