import { TrainOption } from '../../types/booking';
import { TRAIN_IMAGES } from '../../assets/travelImages';

export const TRAIN_INVENTORY: TrainOption[] = [
  // 1. New Delhi (NDLS) -> Varanasi (BSB)
  {
    id: 'tr-ndls-bsb-22436',
    service: 'train',
    operator: 'Indian Railways (IRCTC)',
    identifier: '#22436',
    subType: 'Vande Bharat Express (Varanasi)',
    trainType: 'Vande Bharat',
    originCity: 'New Delhi',
    originCode: 'NDLS',
    originStationOrTerminal: 'New Delhi Railway Station (Platform 16)',
    destinationCity: 'Varanasi',
    destinationCode: 'BSB',
    destinationStationOrTerminal: 'Varanasi Junction (Cantonment)',
    departureTime: '06:00 AM',
    arrivalTime: '02:00 PM',
    duration: '08h 00m',
    stops: 4,
    baseFare: 1750,
    availableUnits: 64,
    rating: 4.9,
    image: TRAIN_IMAGES[0]?.src,
    amenities: ['Catering Included', 'Executive Rotating Seats', 'Bio-Vacuum Restrooms', 'Route Schematics'],
    trainClasses: [
      { className: 'CC', fare: 1750, available: 52, status: 'Available' },
      { className: 'EC', fare: 3300, available: 12, status: 'Available' },
    ],
  },
  {
    id: 'tr-ndls-bsb-12560',
    service: 'train',
    operator: 'Indian Railways (IRCTC)',
    identifier: '#12560',
    subType: 'Shiv Ganga Superfast Express',
    trainType: 'Superfast',
    originCity: 'New Delhi',
    originCode: 'NDLS',
    originStationOrTerminal: 'New Delhi Station (NDLS)',
    destinationCity: 'Varanasi',
    destinationCode: 'BSB',
    destinationStationOrTerminal: 'Varanasi Junction',
    departureTime: '08:05 PM',
    arrivalTime: '06:10 AM',
    duration: '10h 05m',
    stops: 2,
    baseFare: 495,
    availableUnits: 80,
    rating: 4.7,
    image: TRAIN_IMAGES[4]?.src,
    amenities: ['Overnight Sleeper', 'Pantry Car', 'Clean Bedroll', 'Charging Sockets'],
    trainClasses: [
      { className: 'SL', fare: 495, available: 45, status: 'Available' },
      { className: '3A', fare: 1280, available: 25, status: 'Available' },
      { className: '2A', fare: 1850, available: 10, status: 'Available' },
    ],
  },

  // 2. Chennai (MAS) -> Bengaluru (SBC)
  {
    id: 'tr-mas-sbc-20607',
    service: 'train',
    operator: 'Indian Railways (IRCTC)',
    identifier: '#20607',
    subType: 'Vande Bharat Express (Mysuru)',
    trainType: 'Vande Bharat',
    originCity: 'Chennai',
    originCode: 'MAS',
    originStationOrTerminal: 'Puratchi Thalaivar Dr. MGR Central',
    destinationCity: 'Bengaluru',
    destinationCode: 'SBC',
    destinationStationOrTerminal: 'KSR Bengaluru City Junction',
    departureTime: '05:50 AM',
    arrivalTime: '10:15 AM',
    duration: '04h 25m',
    stops: 2,
    baseFare: 995,
    availableUnits: 92,
    rating: 4.9,
    image: TRAIN_IMAGES[0]?.src,
    amenities: ['Morning Breakfast Service', 'Panoramic Sealed Windows', '160 km/h Corridor', 'Infotainment'],
    trainClasses: [
      { className: 'CC', fare: 995, available: 78, status: 'Available' },
      { className: 'EC', fare: 1885, available: 14, status: 'Available' },
    ],
  },
  {
    id: 'tr-mas-sbc-12028',
    service: 'train',
    operator: 'Indian Railways (IRCTC)',
    identifier: '#12028',
    subType: 'KSR Bengaluru Shatabdi Express',
    trainType: 'Shatabdi',
    originCity: 'Chennai',
    originCode: 'MAS',
    originStationOrTerminal: 'Chennai Central (MAS)',
    destinationCity: 'Bengaluru',
    destinationCode: 'SBC',
    destinationStationOrTerminal: 'KSR Bengaluru Station',
    departureTime: '05:30 PM',
    arrivalTime: '10:30 PM',
    duration: '05h 00m',
    stops: 3,
    baseFare: 915,
    availableUnits: 55,
    rating: 4.8,
    image: TRAIN_IMAGES[2]?.src,
    amenities: ['Evening Snacks & Dinner', 'Executive AC Comfort', 'Punctual Intercity Dispatch'],
    trainClasses: [
      { className: 'CC', fare: 915, available: 45, status: 'Available' },
      { className: 'EC', fare: 1780, available: 10, status: 'Available' },
    ],
  },

  // 3. New Delhi (NDLS) -> Mumbai Central (MMCT)
  {
    id: 'tr-ndls-mmct-12952',
    service: 'train',
    operator: 'Indian Railways (IRCTC)',
    identifier: '#12952',
    subType: 'New Delhi Mumbai Rajdhani Express',
    trainType: 'Rajdhani',
    originCity: 'New Delhi',
    originCode: 'NDLS',
    originStationOrTerminal: 'New Delhi Station (NDLS)',
    destinationCity: 'Mumbai',
    destinationCode: 'MMCT',
    destinationStationOrTerminal: 'Mumbai Central Terminus',
    departureTime: '04:55 PM',
    arrivalTime: '08:35 AM',
    duration: '15h 40m',
    stops: 6,
    baseFare: 1850,
    availableUnits: 38,
    rating: 4.8,
    image: TRAIN_IMAGES[1]?.src,
    amenities: ['Overnight Sleeper Berths', 'Complimentary Dinner & Morning Tea', 'Premier Right-of-Way', 'Clean Linen'],
    trainClasses: [
      { className: '3A', fare: 1850, available: 22, status: 'Available' },
      { className: '2A', fare: 2650, available: 11, status: 'Available' },
      { className: '1A', fare: 4450, available: 5, status: 'Available' },
    ],
  },
  {
    id: 'tr-ndls-mmct-12954',
    service: 'train',
    operator: 'Indian Railways (IRCTC)',
    identifier: '#12954',
    subType: 'August Kranti Tejas Rajdhani Express',
    trainType: 'Tejas',
    originCity: 'New Delhi',
    originCode: 'NDLS',
    originStationOrTerminal: 'Hazrat Nizamuddin (NZM)',
    destinationCity: 'Mumbai',
    destinationCode: 'MMCT',
    destinationStationOrTerminal: 'Mumbai Central (MMCT)',
    departureTime: '05:15 PM',
    arrivalTime: '10:05 AM',
    duration: '16h 50m',
    stops: 10,
    baseFare: 1780,
    availableUnits: 42,
    rating: 4.7,
    image: TRAIN_IMAGES[5]?.src,
    amenities: ['Smart Tejas Coaches', 'Bio-Vacuum Toilets', 'Catering Included', 'Automatic Sensor Doors'],
    trainClasses: [
      { className: '3A', fare: 1780, available: 26, status: 'Available' },
      { className: '2A', fare: 2590, available: 12, status: 'Available' },
      { className: '1A', fare: 4320, available: 4, status: 'Available' },
    ],
  },

  // 4. New Delhi (NDLS) -> Rani Kamalapati / Bhopal (RKMP)
  {
    id: 'tr-ndls-rkmp-12002',
    service: 'train',
    operator: 'Indian Railways (IRCTC)',
    identifier: '#12002',
    subType: 'Bhopal Shatabdi Express',
    trainType: 'Shatabdi',
    originCity: 'New Delhi',
    originCode: 'NDLS',
    originStationOrTerminal: 'New Delhi Station',
    destinationCity: 'Bhopal',
    destinationCode: 'RKMP',
    destinationStationOrTerminal: 'Rani Kamalapati Station',
    departureTime: '06:00 AM',
    arrivalTime: '02:40 PM',
    duration: '08h 40m',
    stops: 8,
    baseFare: 950,
    availableUnits: 48,
    rating: 4.6,
    image: TRAIN_IMAGES[2]?.src,
    amenities: ['Day Intercity Speed', 'Morning Breakfast & Newspapers', 'Executive Class Option'],
    trainClasses: [
      { className: 'CC', fare: 950, available: 38, status: 'Available' },
      { className: 'EC', fare: 1850, available: 10, status: 'Available' },
    ],
  },

  // 5. New Delhi (NDLS) -> Sealdah / Kolkata (SDAH)
  {
    id: 'tr-ndls-sdah-12260',
    service: 'train',
    operator: 'Indian Railways (IRCTC)',
    identifier: '#12260',
    subType: 'Sealdah Duronto Express',
    trainType: 'Duronto',
    originCity: 'New Delhi',
    originCode: 'NDLS',
    originStationOrTerminal: 'New Delhi Station',
    destinationCity: 'Kolkata',
    destinationCode: 'SDAH',
    destinationStationOrTerminal: 'Sealdah Station',
    departureTime: '08:15 PM',
    arrivalTime: '12:45 PM',
    duration: '16h 30m',
    stops: 3,
    baseFare: 720,
    availableUnits: 26,
    rating: 4.7,
    image: TRAIN_IMAGES[3]?.src,
    amenities: ['Non-Stop Point to Point', 'Pantry Car Onboard', 'Dedicated Security Squad'],
    trainClasses: [
      { className: 'SL', fare: 720, available: 8, status: 'Available' },
      { className: '3A', fare: 1650, available: 12, status: 'Available' },
      { className: '2A', fare: 2350, available: 4, status: 'Available' },
      { className: '1A', fare: 3950, available: 2, status: 'Available' },
    ],
  },

  // 6. Mumbai Central (MMCT) -> Ahmedabad (ADI)
  {
    id: 'tr-mmct-adi-82902',
    service: 'train',
    operator: 'IRCTC Corporate Rail',
    identifier: '#82902',
    subType: 'Tejas Express (Ahmedabad - Mumbai)',
    trainType: 'Tejas',
    originCity: 'Mumbai',
    originCode: 'MMCT',
    originStationOrTerminal: 'Mumbai Central',
    destinationCity: 'Ahmedabad',
    destinationCode: 'ADI',
    destinationStationOrTerminal: 'Ahmedabad Junction (Kalupur)',
    departureTime: '03:40 PM',
    arrivalTime: '10:05 PM',
    duration: '06h 25m',
    stops: 5,
    baseFare: 1950,
    availableUnits: 72,
    rating: 4.8,
    image: TRAIN_IMAGES[5]?.src,
    amenities: ['Hostess Service', 'Automatic Sliding Doors', 'Onboard Infotainment', 'Delay Compensation Guarantee'],
    trainClasses: [
      { className: 'CC', fare: 1950, available: 58, status: 'Available' },
      { className: 'EC', fare: 3450, available: 14, status: 'Available' },
    ],
  },

  // 7. Bengaluru (SBC) -> Hyderabad (HYB)
  {
    id: 'tr-sbc-hyb-20704',
    service: 'train',
    operator: 'Indian Railways (IRCTC)',
    identifier: '#20704',
    subType: 'Kacheguda Vande Bharat Express',
    trainType: 'Vande Bharat',
    originCity: 'Bengaluru',
    originCode: 'SBC',
    originStationOrTerminal: 'Yesvantpur Junction (YPR)',
    destinationCity: 'Hyderabad',
    destinationCode: 'HYB',
    destinationStationOrTerminal: 'Kacheguda Station',
    departureTime: '02:45 PM',
    arrivalTime: '11:15 PM',
    duration: '08h 30m',
    stops: 4,
    baseFare: 1600,
    availableUnits: 45,
    rating: 4.9,
    image: TRAIN_IMAGES[0]?.src,
    amenities: ['High-Speed Semi-Express', 'Tea & Dinner Included', 'Bio-Vacuum Toilets'],
    trainClasses: [
      { className: 'CC', fare: 1600, available: 35, status: 'Available' },
      { className: 'EC', fare: 2950, available: 10, status: 'Available' },
    ],
  },
];
